[package]
name = "merkle_tree_csv"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.3"
rs_merkle = "1.4.2"
ark-bn254 = "0.4.0"
light-poseidon = "0.2.0"
num-bigint = "0.4.4"

[[bin]]
name = "cool-tool"
path = "scripts/merkle_tree.rs"